### ISSUE TITLE
Create readme

### ISSUE THREAD

**Issue by Abbaasiz** [Abbaasiz/travel_away#13]
Create the following sections in the README:

- Overview: Abbaas
- Wireframes section: Noora
- Features: Mohammed

**Comment by Noora235** [comment]
Last version of the readme.md for the services.html page.
![New Wireframe 2](https://github.com/Abbaasiz/travel_away/assets/148103026/980b2ea1-b3fd-47e5-a2b5-c203a7dcc2b3)
