### ISSUE TITLE
Create wireframes for each page

### ISSUE THREAD

**Issue by Abbaasiz** [Abbaasiz/travel_away#5]

**Comment by Abbaasiz** [comment]
Mohamed - destinations page
Abbaas - Booking and gallery pages
Noora - Services page

**Comment by Abbaasiz** [comment]
Wireframes for booking and gallery pages

**Comment by Noora235** [comment]
Updated new wireframe for services
![New Wireframe 2](https://github.com/Abbaasiz/travel_away/assets/148103026/137e04ab-9a12-4e10-abfb-ff3c4b3cf8c7)

**Comment by Noora235** [comment]
Lates version of the services.html wireframe.
![New Wireframe 2](https://github.com/Abbaasiz/travel_away/assets/148103026/d0b77746-994b-4b2d-b5af-df6641e40ca5)
